# Generated by Django 5.1.2 on 2024-11-27 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_embedobject"),
    ]

    operations = [
        migrations.AddField(
            model_name="kitchenaimanagement",
            name="jupyter_host",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="kitchenaimanagement",
            name="jupyter_port",
            field=models.CharField(default="8888", max_length=255),
        ),
        migrations.AddField(
            model_name="kitchenaimanagement",
            name="jupyter_protocol",
            field=models.CharField(default="http", max_length=255),
        ),
        migrations.AddField(
            model_name="kitchenaimanagement",
            name="jupyter_token",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.CreateModel(
            name="KitchenAIModule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "kitchen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.kitchenaimanagement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
