# Generated by Django 5.1.2 on 2024-11-27 00:37

import kitchenai.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_kitchenaimanagement_jupyter_host_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kitchenaimodule",
            name="file",
            field=models.FileField(
                default="defaults/default_file.txt",
                upload_to=kitchenai.core.models.module_directory_path,
            ),
        ),
        migrations.AddField(
            model_name="kitchenaimodule",
            name="jupyter_path",
            field=models.CharField(default="", max_length=255),
        ),
    ]
