# Generated by Django 5.1.2 on 2024-11-27 00:37

import kitchenai.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_kitchenaimodule_file_kitchenaimodule_jupyter_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kitchenaimodule",
            name="file",
            field=models.FileField(
                upload_to=kitchenai.core.models.module_directory_path
            ),
        ),
    ]
