# Generated by Django 5.1.2 on 2025-01-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bento", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteclient",
            name="client_id",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
