# Generated by Django 5.1.2 on 2025-01-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bento", "0002_alter_remoteclient_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteclient",
            name="client_id",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
