# Generated by Django 5.1.2 on 2024-10-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_kitchenaimanagement_kitchenaimodules_delete_core"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kitchenaimodules",
            name="id",
        ),
        migrations.AlterField(
            model_name="kitchenaimodules",
            name="name",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
