# Generated by Django 5.1.2 on 2024-12-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0002_plugin_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plugin",
            name="enabled",
        ),
    ]
